-- 创建用户表
CREATE TABLE T_USER(
	ID NUMBER(6) PRIMARY KEY,
	USERNAME VARCHAR2(20) NOT NULL UNIQUE,
	USERPWD VARCHAR2(20) NOT NULL,
	USERTYPE NUMBER(3) NOT NULL
);

INSERT INTO T_USER(ID,USERNAME,USERPWD,USERTYPE) VALUES(1,'admin','admin',1);

-- 创建用户ID序列
CREATE SEQUENCE T_USER_ID_SEQ 
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 创建车数据表
CREATE TABLE T_CAR(
	CID NUMBER(6) PRIMARY KEY,
	CARMODEL VARCHAR2(20) NOT NULL,
	CARNUMBER VARCHAR2(20) NOT NULL,
	CARDESC VARCHAR2(50) NOT NULL,
	COLOR VARCHAR2(20),
	PRICE NUMBER(15,2) NOT NULL,
	CARBRAND NUMBER(6) NOT NULL,
	CARTYPE NUMBER(6) NOT NULL,
	RENTPRICE NUMBER(10,2),
	ISRENT NUMBER(6),
	ISONLINE NUMBER(6),
	CONSTRAINT T_CAR_CARBRAND_FK FOREIGN KEY(CARBRAND) REFERENCES T_CARBRAND(ID),
	CONSTRAINT T_CAR_CARTYPE_FK FOREIGN KEY(CARTYPE) REFERENCES T_CARTYPE(ID)
);

-- 创建车ID的序列
CREATE SEQUENCE T_CAR_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 创建车品牌表
CREATE TABLE T_CARBRAND(
	ID NUMBER(6) PRIMARY KEY ,
	BRANDNAME VARCHAR2(20) NOT NULL
);

-- 创建车品牌id序列
CREATE SEQUENCE T_CARBRAND_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- 创建车类型表
CREATE TABLE T_CARTYPE(
	ID NUMBER(6) PRIMARY KEY,
	TYPENAME VARCHAR2(20) NOT NULL
);

-- 创建类型id序列
CREATE SEQUENCE T_CARTYPE_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 创建租赁表
CREATE TABLE T_RENTRECORD(
	RID NUMBER(6) PRIMARY KEY,
	CID NUMBER(6) NOT NULL,
	CARNAME VARCHAR2(20) NOT NULL,
	U_ID NUMBER (6) NOT NULL,
	UNAME VARCHAR2(20) NOT NULL,
	RENTPRICE NUMBER(10,2) NOT NULL,
	CARBRAND NUMBER(6) NOT NULL,
	RENTTIME VARCHAR2(30) ,
	ALLPRICE NUMBER(10,2) ,
	CARDESC VARCHAR2(50) NOT NULL,
	CARTYPE NUMBER(6),
	RETURNCARTIME VARCHAR2(30),
	RENTSTATUS NUMBER(6) NOT NULL,
	CONSTRAINT T_RENTRECORD_CID_FK FOREIGN KEY(CID) REFERENCES T_CAR(CID),
	CONSTRAINT T_RENTRECORD_UID_FK FOREIGN KEY(U_ID) REFERENCES T_USER(ID)
);

-- 创建租赁id序列
CREATE SEQUENCE T_RENTRECORD_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
